### ISSUE TITLE
AttributeError: module 'mistune' has no attribute 'BlockGrammar' in line 58 of m2r.py

### ISSUE THREAD

**Issue by mcepl** [miyakogi/m2r#66]
When packaging new version of mistune (2.0.0-rc1) is included into openSUSE/Factory, this package’s test suite starts failing:
```
[   32s] + /usr/bin/python3.6 setup.py build '--executable=/usr/bin/python3.6 -s'
[   32s] Traceback (most recent call last):
[   32s]   File "setup.py", line 14, in <module>
[   32s]     from m2r import parse_from_file
[   32s]   File "/home/abuild/rpmbuild/BUILD/m2r-0.2.1/m2r.py", line 58, in <module>
[   32s]     class RestBlockGrammar(mistune.BlockGrammar):
[   32s] AttributeError: module 'mistune' has no attribute 'BlockGrammar'
[   32s] error: Bad exit status from /var/tmp/rpm-tmp.G27V7P (%build)
```
[Complete build log](https://github.com/miyakogi/m2r/files/7589714/_log.txt) with all versions of packages used and steps taken.

**Comment by ahopkins** [comment]
I am getting this as well.

**Comment by crazyscientist** [comment]
This issue seems to be specific to **Python 3.6**. 

With Python 3.8 `m2r==0.2.1` and `mistune==2.0.0` seem to work well together :thinking:

**Comment by mahendrapaipuri** [comment]
I am facing the same issue right now and it looks like `mistune v2.*` versions had huge revamp and there is no `BlockGrammar` class anymore by the looks of it -> https://github.com/lepture/mistune/blob/v2.0.0a1/mistune/__init__.py#L54-L59 . I think `m2r2` needs to constraint the `mistune` version to `<2.0.0` as suggested in one of the above comments?

**Comment by mahendrapaipuri** [comment]
The [PR](https://github.com/miyakogi/m2r/pull/43/files) is waiting to be merged to fix this issue. Seems like this repository is not being maintained anymore.

**Comment by mcepl** [comment]
> The [PR](https://github.com/miyakogi/m2r/pull/43/files) is waiting to be merged to fix this issue. Seems like this repository is not being maintained anymore.

Fixing the issue should actually mean fixing the issue.

**Comment by mcepl** [comment]
Just to confirm that even with m2r-0.2.1 and mistune-2.0.0 I get exactly the same result.

[Complete build log](https://github.com/miyakogi/m2r/files/7675630/_log.txt) showing all packages used and steps taken to achieve the failed test.

**Comment by mahendrapaipuri** [comment]
@mcepl I agree that fixing the issue means revamping `m2r2` with upstream changes in the API of `mistune`. But seems like no one is maintaining this repo anymore. As long as `mistune>=2.0.0` is used to build `m2r2`, this will always break (due to changes in API in `mistune>=2.0.0`). So the quick fix would be to lock `mistune<2.0.0`.

**Comment by ahopkins** [comment]
Sounds like an m2r3 is needed :laughing:

**Comment by mahendrapaipuri** [comment]
Wait, I have just realised that this is indeed "old" repository and the new "m2r2" is a fork of this repo and being actively maintained here -> https://github.com/CrossNox/m2r2 . They have already have a [PR](https://github.com/CrossNox/m2r2/pull/43) on this issue and hopefully it will be released soon.

**Comment by mcepl** [comment]
> They have already have a [PR](https://github.com/CrossNox/m2r2/pull/43) on this issue and hopefully it will be released soon.

And again, that PR is not fix just freezing old version of mistune.

**Comment by Fl4m3Ph03n1x** [comment]
I also have this issue with Python 3.7:

```
- m2r=0.2.1=py_0
- markupsafe=2.0.1=py37h5e8e339_0
- mistune=2.0.0=pyhd8ed1ab_1
```

I am guessing the issue is from mistune 2.0.0.
If the follow semantic versioning, the jump from 1.X to 2.X means backwards incompatible changes to the API.
A revert to an older version might be the actual "fix".

**Comment by mcepl** [comment]
> I am guessing the issue is from mistune 2.0.0. If they follow semantic versioning, the jump from 1.X to 2.X means backwards incompatible changes to the API. A revert to an older version might be the actual "fix".

It is not the fix, it is a workaround. When you make your program dependent on another library, you get yourself into a debt and a dependency on somebody else’s plans, which you have no control over, but to which you have to accommodate. Unless you follow that somebody else’s plans, your package is broken and your users will be unhappy with you. In the end, the easiest thing for me is to get rid of m2r in OpenSUSE, because it is apparently unmaintained.

**Comment by jimhavrilla** [comment]
Can you update pypi with this?

**Comment by jreese** [comment]
> Sounds like an m2r3 is needed 😆

I forked a new project, `sphinx-mdinclude` from m2r2, and did extensive work to upgrade to mistune 2.0. Details available at https://sphinx-mdinclude.readthedocs.io/en/latest/

**Comment by kloczek** [comment]
I just hit the same issue trying generate `jupyter-server` documentation.
Any chance to make new release updated against latest `mistune`?

**Comment by kloczek** [comment]
Any plans to update `m2r` for `mistune` 2.x? 🤔
