### ISSUE TITLE
ImportError: cannot import name 'ErrorString' from 'docutils.core' 

### ISSUE THREAD

**Issue by xnuinside** [miyakogi/m2r#69]
Hi! I previously used m2r successfully, but now got weird issue:

m2r    version      0.2.1

Issue that I see:

Traceback (most recent call last):
  File "/Users/ynvolkova/Library/Caches/pypoetry/virtualenvs/codegraph-yn-VnWyz-py3.10/bin/m2r", line 5, in <module>
    from m2r import main
  File "/Users/ynvolkova/Library/Caches/pypoetry/virtualenvs/codegraph-yn-VnWyz-py3.10/lib/python3.10/site-packages/m2r.py", line 13, in <module>
    from docutils.core import ErrorString
ImportError: cannot import name 'ErrorString' from 'docutils.core' (/Users/ynvolkova/Library/Caches/pypoetry/virtualenvs/codegraph-yn-VnWyz-py3.10/lib/python3.10/site-packages/docutils/core.py)

docutils      version     0.19

**_if downgrade to version 0.18 it will fix the issue, looks like need to freeze dependencies in m2r_**

**Comment by xnuinside** [comment]
nevermind, I see m2r2 exists )
